name: Автоматическая сборка и публикация приложения WordGuessing
run-name: Сборка нового коммита '${{ github.event.head_commit.message }}'

on: [push]
jobs:
  build-linux:
    runs-on: ubuntu-latest
    outputs:
      release_app: ${{ steps.set-output.outputs.release_built }}
    steps:
      - uses: actions/checkout@v4
      - name: Кэш зависимостей
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Сборка бинарного файла
        run: cargo build --release
      - name: Сохранение файла в артифакты
        uses: actions/upload-artifact@v4
        with:
          name: word_guessing
          path: target/release/word_guessing
  build-windows:
    runs-on: windows-latest
    outputs:
      release_app: ${{ steps.set-output.outputs.release_built }}
    steps:
      - uses: actions/checkout@v4
      - name: Кэш зависимостей
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Сборка бинарного файла
        run: cargo build --release
      - name: Сохранение файла в артифакты
        uses: actions/upload-artifact@v4
        with:
          name: word_guessing
          path: target/release/word_guessing.exe
        