name: Автоматическая сборка и публикация приложения WordGuessing
run-name: Версия приложения - ${{ env.CARGO_PKG_VERSION }}. Коммит '${{ github.event.head_commit.message }}'.  

on:
  push:
    branches:
      - main
      - test_actions
jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Кэш зависимостей
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Сборка бинарного файла
        run: cargo build --release
      - name: Сохранение файла в артифакты
        uses: actions/upload-artifact@v4
        with:
          name: word_guessing_linux
          path: target/release/word_guessin
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Кэш зависимостей
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Сборка бинарного файла
        run: cargo build --release
      - name: Сохранение файла в артифакты
        uses: actions/upload-artifact@v4
        with:
          name: word_guessing_windows
          path: target/release/word_guessing.exe
  
  publish:
    runs-on: ubuntu-latest
    needs: [build-linux, build-windows]
    steps:
      - name: Загрузка бинарного файла linux из артефактов
        uses: actions/download-artifact@v4
        with:
          name: word_guessing_linux
          path: artifacts/word_guessing
      - name: Загрузка бинарного файла windows из артефактов
        uses: actions/download-artifact@v4
        with:
          name: word_guessing_windows
          path: artifacts/word_guessing.exe
      - name: Публикация файлов
        run: |
          gh release create --generate-notes artifacts/word_guessing artifacts/word_guessing.exe